export enum PokemonTypeIcon {
    BUG = '/assets/img/typeIcon/bug.svg',
    DARK = '/assets/img/typeIcon/dark.svg',
    DRAGON = '/assets/img/typeIcon/dragon.svg',
    ELECTRIC = '/assets/img/typeIcon/electric.svg',
    FAIRY = '/assets/img/typeIcon/fairy.svg',
    FIGHTING = '/assets/img/typeIcon/fighting.svg',
    FIRE = '/assets/img/typeIcon/fire.svg',
    FLYING = '/assets/img/typeIcon/flying.svg',
    GHOST = '/assets/img/typeIcon/ghost.svg',
    GRASS = '/assets/img/typeIcon/grass.svg',
    GROUND = '/assets/img/typeIcon/ground.svg',
    ICE = '/assets/img/typeIcon/ice.svg',
    NORMAL = '/assets/img/typeIcon/normal.svg',
    POISON = '/assets/img/typeIcon/poison.svg',
    PSYCHIC = '/assets/img/typeIcon/psychic.svg',
    ROCK = '/assets/img/typeIcon/rock.svg',
    STEEL = '/assets/img/typeIcon/steel.svg',
    WATER = '/assets/img/typeIcon/water.svg'
}